"""initial schema

Revision ID: cea3204a984b
Revises: 
Create Date: 2026-08-13 01:03:37.898807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cea3204a984b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_label', sa.String(length=20), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('edd_confirmation', sa.Boolean(), nullable=False),
    sa.Column('edd_reported_consulting', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('claim_weeks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claim_weeks_start_date'), ['start_date'], unique=True)
        batch_op.create_index(batch_op.f('ix_claim_weeks_week_number'), ['week_number'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('google_sub', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('consulting_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('total_hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('total_earned', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('claim_week_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_week_id'], ['claim_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('consulting_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consulting_entries_claim_week_id'), ['claim_week_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consulting_entries_start_date'), ['start_date'], unique=False)

    op.create_table('job_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('job_description_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('resume_key', sa.String(length=512), nullable=True),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('resume_content_type', sa.String(length=120), nullable=True),
    sa.Column('cover_letter_key', sa.String(length=512), nullable=True),
    sa.Column('cover_letter_filename', sa.String(length=255), nullable=True),
    sa.Column('cover_letter_content_type', sa.String(length=120), nullable=True),
    sa.Column('job_description_key', sa.String(length=512), nullable=True),
    sa.Column('job_description_filename', sa.String(length=255), nullable=True),
    sa.Column('job_description_content_type', sa.String(length=120), nullable=True),
    sa.Column('claim_week_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['claim_week_id'], ['claim_weeks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_applications_application_date'), ['application_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_applications_claim_week_id'), ['claim_week_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_applications_claim_week_id'))
        batch_op.drop_index(batch_op.f('ix_job_applications_application_date'))

    op.drop_table('job_applications')
    with op.batch_alter_table('consulting_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consulting_entries_start_date'))
        batch_op.drop_index(batch_op.f('ix_consulting_entries_claim_week_id'))

    op.drop_table('consulting_entries')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('claim_weeks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claim_weeks_week_number'))
        batch_op.drop_index(batch_op.f('ix_claim_weeks_start_date'))

    op.drop_table('claim_weeks')
    # ### end Alembic commands ###
