"""Replace Google OAuth with GitHub OAuth

Revision ID: github_oauth
Revises: cea3204a984b
Create Date: 2026-08-12 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'github_oauth'
down_revision = 'cea3204a984b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_username', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_github_username', ['github_username'])
        batch_op.drop_column('google_sub')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_sub', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint('uq_google_sub', ['google_sub'])
        batch_op.drop_column('github_username')

    # ### end Alembic commands ###
